### ISSUE TITLE
Consider defining an IRI to represent the type of an embedded triple or triple pattern

### ISSUE THREAD

**Issue by kasei** [w3c/rdf-star#77] opened 2020-12-23 01:17 UTC
This would be useful for representing queries and metadata in a structured way. For example, representing a SPARQL* query in a format such as [SPIN](https://spinrdf.org) or indicating the type of a database column using [R2RML's](https://www.w3.org/ns/r2rml) `termType`. This would work alongside other IRIs such as `rdfs:Literal` and `rr:BlankNode`.

**Comment by afs** [comment] 2020-12-23 14:03
Related: SHACL [NodeKind](https://www.w3.org/TR/shacl/#NodeKindConstraintComponent).

**Comment by hartig** [comment] 2021-03-10 21:39
Just saw that this issue is a duplicate of #102

**Comment by pchampin** [comment] 2021-03-11 17:04
That's right. Although this one was here first, most of the discussion happened on #102, so I'll close this one as a dublicate. No offense @kasei ;)

**Closed by pchampin** 2021-03-11 17:04 UTC
Labels: duplicate
