### ISSUE TITLE
RDF* Dataset

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star#17] opened 2020-10-14 09:03 UTC
Should this CG extend the work to define an "RDF* dataset"?

Or is that only a collection of RDF* graphs?

Example:

For systems where the default graph is the union of named graphs, the named graphs form a means to manage data which is accessed as a union of all the data in the store.

But a subgraph of an RDF* graph may not be a legal RDF* graph (PG mode) if the annotation is separate from the target triple.

This may be too ambitious at this time because it gives rise to multiple independent annotations of the same triple.

**Comment by pchampin** [comment] 2020-10-14 09:41
It is actually already done :) https://w3c.github.io/rdf-star/#dfn-dataset

> But a subgraph of an RDF* graph may not be a legal RDF* graph (PG mode) if the annotation is separate from the target triple.

As the current abstract syntax is more akin to SA mode than PG mode, the problem is avoided.

> This may be too ambitious at this time because it gives rise to multiple independent annotations of the same triple.

You mean having something like this (using a hypothetic TriG*)?
```
:g1 { :bob :age 42 {| :statedBy :alice; :statedOn "2020-10-11"^^xsd:date |} }
:g2 { :bob :age 42 {| :statedBy :bob; :statedOn "2020-10-12"^^xsd:date |} }
```
Since RDF* triples represent "the triple in general", and not "a particular occurrence of the triple", I would argue that this is bad modelling, just like the following would be bad modelling...
```
:g1 { :bob :marriedTo :alice; :marriedOn "2018-10-11"^^xsd:date }
:g2 { :bob :marriedTo :eve; :marriedOn "2020-10-12"^^xsd:date }

```
But granted, this is a common use case for triple annotations, so there should be a clear explanation somewhere on how to model this properly.

**Comment by afs** [comment] 2020-10-14 10:23
That is the weakest possible definition of RDF* dataset but excludes the use case of a default union graph in the dataset, which is quite common.

More basic example:
```
:g1 { << :bob :age 42 >> :statedBy :alice; :statedOn "2020-10-11"^^xsd:date }
:g2 { :bob :age 42 }
```
and the union that appears for query is the RDF* graph.
```
<< :bob :age 42 >> :statedBy :alice; :statedOn "2020-10-11"^^xsd:date .
:bob :age 42 .
```

Going on to differing accounts in different graphs is whole other level.

**Comment by pchampin** [comment] 2020-10-14 12:05
> That is the weakest possible definition of RDF* dataset

It is a straighforward extension of [RDF's definition](https://www.w3.org/TR/rdf11-concepts/#section-dataset).

> [It] excludes the use case of a default union graph in the dataset

It neither enforce it nor prevents it, again, just like the original RDF definition.
In your example above, the 2nd part is indeed the union of the two named graphs in the 1st part. What is the problem?

**Comment by afs** [comment] 2020-10-14 13:02
RDF* in the paper does not allow the graph of one triple:
```
:g1 { << :bob :age 42 >> :statedBy :alice }
```
A subgraph of an RDF graph is any subset of the triples.
This is not true for RDF*/paper.

The union is legal RDF* but the constituents are not.

**Comment by hartig** [comment] 2020-10-14 18:52
> A subgraph of an RDF graph is any subset of the triples. This is not true for RDF*/paper.
>
> The union is legal RDF* but the constituents are not.

If I understand the problem correctly, then the crux of it is that the definitions in the paper capture PG mode (because that was my implicit assumption at the time). If we assume SA mode instead, then the problem disappears. Do you agree?

**Comment by afs** [comment] 2020-10-15 08:19
Yes - it's the feature of SA mode that causes the union/subgraph issue.

**Comment by hartig** [comment] 2020-10-15 12:15
Andy, do you really mean SA mode now, or was that a typo?
I suggested that the problem is caused by PG mode and disappears under SA mode.

**Comment by afs** [comment] 2020-10-15 15:06
Good catch! rather important!! I've editted the comment. We and delete our meta-comments.

**Comment by pchampin** [comment] 2020-10-19 10:20
darn, I removed the meta-comments, but then realized I might have been to hasty... @afs, you don't seem to have edited your last comment above. As I understand, you meant 
> Yes - it's the feature of **PG** mode that causes the union/subgraph issue.
right?

If so, are you satisfied with the answer and agreeing to close this issue?

**Comment by afs** [comment] 2020-10-23 15:07
> If so, are you satisfied with the answer

Yes.

> and agreeing to close this issue?

Fine - the "cross-reference" issue does not arise if triple-terms are not always linked to triples.

**Closed** 2020-10-27 08:07 UTC
