### ISSUE TITLE
What's in a name? RDF*, RDF+, RDF#, etc.

### ISSUE THREAD

**Issue by TallTed** [w3c/rdf-star#59] opened 2020-12-09 22:11 UTC
RDF* is an unsearchable string, but searches for RDF do bring it to light occasionally.

This evening, while searching for something else, I randomly discovered the existence of the [RDF#](https://blogs.oracle.com/oraclespatial/rdf-extending-rdf-to-support-named-triples) proposal, which led me to the [RDF+](https://web.archive.org/web/20170707220419/http://wwwconference.org/www2008/papers/pdf/p625-schueler.pdf) proposal (which is no longer at the URL the RDF# paper linked to, this link takes you into the Internet Archive for it).

(I am not prepared to do a full analysis of either of these. I do wonder whether anyone else has done some comparison, and could add such to this repo...)

Unsurprisingly, neither of the others included a searchable version of their name (e.g., rdf-hash, rdf-plus).  Being unsearchable might help explain how they remain apparently unpopular.  It doesn't do anything to explain the popularity of RDF*, however, which I continue to believe is in desperate need of a renaming.

(What's the next one to be, `RDF**`? `RDF*+#`?)

**Comment by pchampin** [comment] 2020-12-10 07:46
Thinking out loud:
* on the one hand, RDF* is already quite popular, as you notice, so renaming it might confuse people,
* on the other hand, RDF* is also already quite confusing (SA mode or PG mode?T unique triples as per the definitions or triple instances as per the examples?), so a new name might help get rid of the confusion (once we are clear on what *that* name denotes...).

If we decide to keep the original name, clearly we need to be careful to also use the "alphabetized" version "rdf-star", as is already the case in most URLs related to the project.

**Comment by akuckartz** [comment] 2020-12-10 10:24
I think this issue is a duplicate of #20 and therefore should be closed.

**Closed** 2020-12-10 10:50 UTC
Labels: duplicate

**Comment by TallTed** [comment] 2020-12-10 14:47
Ah, I hadn't reached #20 in my long slog through the work I've missed in the past year (but I had reached a level of frustration during that slog)...

I've moved my thinking over there.
